<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Flight;

class FlightSeeder extends Seeder
{
    public function run(): void
    {
        $flights = [
            [
                'flight_number'      => 'IB8301',
                'origin_loc_id'      => 1,
                'destination_loc_id' => 3,
                'airline'            => 'Iberia',
                'departure'          => '2026-07-15 10:30:00',
                'arrival'            => '2026-07-16 07:15:00',
                'capacity'           => 280,
                'price'              => 745.00,
                'duration_time'      => '13h 45m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Iberia/Iberia.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 45, 'Asiento extra legroom' => 25, 'Embarque prioritario' => 15],
            ],
            [
                'flight_number'      => 'IB8302',
                'origin_loc_id'      => 3,
                'destination_loc_id' => 1,
                'airline'            => 'Iberia',
                'departure'          => '2026-07-25 14:00:00',
                'arrival'            => '2026-07-26 07:30:00',
                'capacity'           => 280,
                'price'              => 720.00,
                'duration_time'      => '13h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Iberia/Iberia.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 45, 'Asiento extra legroom' => 25, 'Embarque prioritario' => 15],
            ],
            [
                'flight_number'      => 'EK075',
                'origin_loc_id'      => 1,
                'destination_loc_id' => 5,
                'airline'            => 'Emirates',
                'departure'          => '2026-08-01 08:00:00',
                'arrival'            => '2026-08-01 19:00:00',
                'capacity'           => 350,
                'price'              => 389.00,
                'duration_time'      => '7h 00m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Emirates/Emirates.jpg',
                'extras'             => ['Maleta cabina (7kg)' => 0, 'Maleta facturada (30kg)' => 0, 'Asiento con reclinación completa' => 0, 'Menú especial' => 0],
            ],
            [
                'flight_number'      => 'EK076',
                'origin_loc_id'      => 5,
                'destination_loc_id' => 1,
                'airline'            => 'Emirates',
                'departure'          => '2026-08-11 21:30:00',
                'arrival'            => '2026-08-12 06:00:00',
                'capacity'           => 350,
                'price'              => 375.00,
                'duration_time'      => '7h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Emirates/Emirates.jpg',
                'extras'             => ['Maleta cabina (7kg)' => 0, 'Maleta facturada (30kg)' => 0, 'Asiento con reclinación completa' => 0, 'Menú especial' => 0],
            ],
            [
                'flight_number'      => 'LH404',
                'origin_loc_id'      => 9,
                'destination_loc_id' => 1,
                'airline'            => 'Lufthansa',
                'departure'          => '2026-06-20 07:15:00',
                'arrival'            => '2026-06-20 10:30:00',
                'capacity'           => 190,
                'price'              => 145.00,
                'duration_time'      => '2h 15m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Lufthansa/lufthansa.jpg',
                'extras'             => ['Maleta cabina (8kg)' => 0, 'Maleta facturada (23kg)' => 30, 'Embarque prioritario' => 12, 'Seguro de viaje' => 18],
            ],
            [
                'flight_number'      => 'LH405',
                'origin_loc_id'      => 1,
                'destination_loc_id' => 9,
                'airline'            => 'Lufthansa',
                'departure'          => '2026-06-20 13:00:00',
                'arrival'            => '2026-06-20 15:30:00',
                'capacity'           => 190,
                'price'              => 138.00,
                'duration_time'      => '2h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Lufthansa/lufthansa.jpg',
                'extras'             => ['Maleta cabina (8kg)' => 0, 'Maleta facturada (23kg)' => 30, 'Embarque prioritario' => 12, 'Seguro de viaje' => 18],
            ],
            [
                'flight_number'      => 'DL1248',
                'origin_loc_id'      => 4,
                'destination_loc_id' => 8,
                'airline'            => 'Delta',
                'departure'          => '2026-06-15 06:30:00',
                'arrival'            => '2026-06-15 10:45:00',
                'capacity'           => 230,
                'price'              => 285.00,
                'duration_time'      => '4h 15m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Delta/Delta.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 35, 'Asiento extra legroom' => 22, 'Seguro de cancelación' => 25],
            ],
            [
                'flight_number'      => 'DL1249',
                'origin_loc_id'      => 8,
                'destination_loc_id' => 4,
                'airline'            => 'Delta',
                'departure'          => '2026-06-25 12:00:00',
                'arrival'            => '2026-06-25 16:30:00',
                'capacity'           => 230,
                'price'              => 295.00,
                'duration_time'      => '4h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Delta/Delta.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 35, 'Asiento extra legroom' => 22, 'Seguro de cancelación' => 25],
            ],
            [
                'flight_number'      => 'JL775',
                'origin_loc_id'      => 3,
                'destination_loc_id' => 10,
                'airline'            => 'Japan Airlines',
                'departure'          => '2026-09-10 11:00:00',
                'arrival'            => '2026-09-10 23:30:00',
                'capacity'           => 300,
                'price'              => 620.00,
                'duration_time'      => '9h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/JapanAirlines/JapanAirlines.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 0, 'Almuerzo a bordo' => 0, 'Asiento preferente' => 40],
            ],
            [
                'flight_number'      => 'JL034',
                'origin_loc_id'      => 3,
                'destination_loc_id' => 4,
                'airline'            => 'Japan Airlines',
                'departure'          => '2026-09-05 10:30:00',
                'arrival'            => '2026-09-05 10:00:00',
                'capacity'           => 300,
                'price'              => 810.00,
                'duration_time'      => '12h 30m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/JapanAirlines/JapanAirlines.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 0, 'Almuerzo a bordo' => 0, 'Asiento preferente' => 40],
            ],
            [
                'flight_number'      => 'FR4521',
                'origin_loc_id'      => 9,
                'destination_loc_id' => 7,
                'airline'            => 'Ryanair',
                'departure'          => '2026-07-01 06:00:00',
                'arrival'            => '2026-07-01 09:15:00',
                'capacity'           => 189,
                'price'              => 72.00,
                'duration_time'      => '2h 15m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Ryanair/ryanair.jpg',
                'extras'             => ['Maleta pequeña (40x20x25cm)' => 0, 'Maleta cabina (10kg)' => 8, 'Maleta facturada (20kg)' => 25, 'Embarque prioritario' => 6],
            ],
            [
                'flight_number'      => 'FR4522',
                'origin_loc_id'      => 7,
                'destination_loc_id' => 9,
                'airline'            => 'Ryanair',
                'departure'          => '2026-07-08 10:30:00',
                'arrival'            => '2026-07-08 12:45:00',
                'capacity'           => 189,
                'price'              => 68.00,
                'duration_time'      => '2h 15m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Ryanair/ryanair.jpg',
                'extras'             => ['Maleta pequeña (40x20x25cm)' => 0, 'Maleta cabina (10kg)' => 8, 'Maleta facturada (20kg)' => 25, 'Embarque prioritario' => 6],
            ],
            [
                'flight_number'      => 'VY8531',
                'origin_loc_id'      => 7,
                'destination_loc_id' => 2,
                'airline'            => 'Vueling',
                'departure'          => '2026-08-20 07:30:00',
                'arrival'            => '2026-08-20 09:45:00',
                'capacity'           => 180,
                'price'              => 89.00,
                'duration_time'      => '1h 50m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Vueling/Vueling.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 22, 'Asiento reservado' => 8, 'Embarque prioritario' => 10],
            ],
            [
                'flight_number'      => 'VY8532',
                'origin_loc_id'      => 2,
                'destination_loc_id' => 7,
                'airline'            => 'Vueling',
                'departure'          => '2026-08-27 18:00:00',
                'arrival'            => '2026-08-27 20:10:00',
                'capacity'           => 180,
                'price'              => 85.00,
                'duration_time'      => '1h 50m',
                'stops'              => 0,
                'image_url'          => 'ImagesProduccion/Airlines/Vueling/Vueling.jpg',
                'extras'             => ['Maleta cabina (10kg)' => 0, 'Maleta facturada (23kg)' => 22, 'Asiento reservado' => 8, 'Embarque prioritario' => 10],
            ],
            [
                'flight_number'      => 'QR7722',
                'origin_loc_id'      => 5,
                'destination_loc_id' => 6,
                'airline'            => 'Qatar Airways',
                'departure'          => '2026-10-01 02:00:00',
                'arrival'            => '2026-10-01 16:00:00',
                'capacity'           => 320,
                'price'              => 490.00,
                'duration_time'      => '8h 00m',
                'stops'              => 1,
                'image_url'          => 'ImagesProduccion/Airlines/Qatar/Qatar.jpg',
                'extras'             => ['Maleta facturada (30kg)' => 0, 'Menú gourmet a bordo' => 0, 'Asiento Business' => 250, 'Sala VIP aeropuerto' => 35],
            ],
            [
                'flight_number'      => 'QR7723',
                'origin_loc_id'      => 6,
                'destination_loc_id' => 5,
                'airline'            => 'Qatar Airways',
                'departure'          => '2026-10-11 18:00:00',
                'arrival'            => '2026-10-12 07:00:00',
                'capacity'           => 320,
                'price'              => 510.00,
                'duration_time'      => '8h 00m',
                'stops'              => 1,
                'image_url'          => 'ImagesProduccion/Airlines/Qatar/Qatar.jpg',
                'extras'             => ['Maleta facturada (30kg)' => 0, 'Menú gourmet a bordo' => 0, 'Asiento Business' => 250, 'Sala VIP aeropuerto' => 35],
            ],
        ];

        foreach ($flights as $data) {
            Flight::create($data);
        }
    }
}
