<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Reservation;

class ReservationSeeder extends Seeder
{
    public function run(): void
    {
        $reservations = [
            [
                'user_id'        => 3,
                'hotel_id'       => 5,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => null,
                'total_price'    => 2450.00,
                'contact_name'   => 'Luis García',
                'contact_dni'    => '12345678A',
                'contact_email'  => 'premium@travelai.com',
                'contact_phone'  => '+34 600 000 003',
                'passengers_data'=> [['nombre' => 'Luis García', 'dni' => '12345678A']],
                'extras'         => ['Desayuno incluido' => 30],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 3,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => 3,
                'total_price'    => 2980.00,
                'contact_name'   => 'Luis García',
                'contact_dni'    => '12345678A',
                'contact_email'  => 'premium@travelai.com',
                'contact_phone'  => '+34 600 000 003',
                'passengers_data'=> [['nombre' => 'Luis García', 'dni' => '12345678A'], ['nombre' => 'Carmen García', 'dni' => '87654321B']],
                'extras'         => ['Desayuno japonés' => 25],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 4,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => 7,
                'activity_id'    => null,
                'package_id'     => null,
                'total_price'    => 285.00,
                'contact_name'   => 'María López',
                'contact_dni'    => '23456789B',
                'contact_email'  => 'usuario@travelai.com',
                'contact_phone'  => '+34 600 000 004',
                'passengers_data'=> [['nombre' => 'María López', 'dni' => '23456789B']],
                'extras'         => null,
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 4,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => 8,
                'package_id'     => null,
                'total_price'    => 55.00,
                'contact_name'   => 'María López',
                'contact_dni'    => '23456789B',
                'contact_email'  => 'usuario@travelai.com',
                'contact_phone'  => '+34 600 000 004',
                'passengers_data'=> [['nombre' => 'María López', 'dni' => '23456789B']],
                'extras'         => ['Pack fotos underwater' => 25],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 5,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => 8,
                'total_price'    => 1099.00,
                'contact_name'   => 'Jorge Fernández',
                'contact_dni'    => '34567890C',
                'contact_email'  => 'jorge.fernandez@email.com',
                'contact_phone'  => '+34 611 223 344',
                'passengers_data'=> [['nombre' => 'Jorge Fernández', 'dni' => '34567890C'], ['nombre' => 'Elena Fernández', 'dni' => '34567891C']],
                'extras'         => ['Todo incluido' => 0],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 6,
                'hotel_id'       => 6,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => null,
                'total_price'    => 910.00,
                'contact_name'   => 'Sofía Torres',
                'contact_dni'    => '45678901D',
                'contact_email'  => 'sofia.torres@email.com',
                'contact_phone'  => '+34 622 334 455',
                'passengers_data'=> [['nombre' => 'Sofía Torres', 'dni' => '45678901D']],
                'extras'         => ['Desayuno balinés' => 15],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 6,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => 6,
                'package_id'     => null,
                'total_price'    => 65.00,
                'contact_name'   => 'Sofía Torres',
                'contact_dni'    => '45678901D',
                'contact_email'  => 'sofia.torres@email.com',
                'contact_phone'  => '+34 622 334 455',
                'passengers_data'=> [['nombre' => 'Sofía Torres', 'dni' => '45678901D']],
                'extras'         => null,
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 7,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => 1,
                'total_price'    => 1540.00,
                'contact_name'   => 'Pablo Sánchez',
                'contact_dni'    => '56789012E',
                'contact_email'  => 'pablo.sanchez@email.com',
                'contact_phone'  => '+34 633 445 566',
                'passengers_data'=> [['nombre' => 'Pablo Sánchez', 'dni' => '56789012E']],
                'extras'         => ['Desayuno incluido' => 20],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 8,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => 13,
                'activity_id'    => null,
                'package_id'     => null,
                'total_price'    => 89.00,
                'contact_name'   => 'Laura Jiménez',
                'contact_dni'    => '67890123F',
                'contact_email'  => 'laura.jimenez@email.com',
                'contact_phone'  => '+34 644 556 677',
                'passengers_data'=> [['nombre' => 'Laura Jiménez', 'dni' => '67890123F']],
                'extras'         => null,
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 8,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => 9,
                'total_price'    => 1349.00,
                'contact_name'   => 'Laura Jiménez',
                'contact_dni'    => '67890123F',
                'contact_email'  => 'laura.jimenez@email.com',
                'contact_phone'  => '+34 644 556 677',
                'passengers_data'=> [['nombre' => 'Laura Jiménez', 'dni' => '67890123F'], ['nombre' => 'Marcos Jiménez', 'dni' => '67890124F']],
                'extras'         => ['Desayuno inglés' => 20],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 5,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => 7,
                'package_id'     => null,
                'total_price'    => 75.00,
                'contact_name'   => 'Jorge Fernández',
                'contact_dni'    => '34567890C',
                'contact_email'  => 'jorge.fernandez@email.com',
                'contact_phone'  => '+34 611 223 344',
                'passengers_data'=> [['nombre' => 'Jorge Fernández', 'dni' => '34567890C']],
                'extras'         => ['Pack fotos y vídeo profesional' => 22],
                'status'         => 'confirmed',
            ],
            [
                'user_id'        => 3,
                'hotel_id'       => null,
                'hotel_room_id'  => null,
                'flight_id'      => null,
                'activity_id'    => null,
                'package_id'     => 5,
                'total_price'    => 3299.00,
                'contact_name'   => 'Luis García',
                'contact_dni'    => '12345678A',
                'contact_email'  => 'premium@travelai.com',
                'contact_phone'  => '+34 600 000 003',
                'passengers_data'=> [['nombre' => 'Luis García', 'dni' => '12345678A']],
                'extras'         => ['Envoltura de oro 24k' => 60],
                'status'         => 'confirmed',
            ],
        ];

        foreach ($reservations as $data) {
            Reservation::create($data);
        }
    }
}
